In [1]:
import pandas as pd
import numpy as np

print("Insurance Claims Analytics Project Started")

Insurance Claims Analytics Project Started

In [2]:
import pandas as pd
import numpy as np

np.random.seed(42)

num_records = 1000

provinces = ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo", "Mpumalanga", "Northern Cape", "North West", "Western Cape"]

claim_types = ["Business Insurance", "Health Insurance", "Home Insurance", "Life Insurance", "Motor Vehicle"]

claim_status = ["Approved", "Pending", "Rejected"]

# Full range: Jan to September 2025
full_dates = pd.date_range(start="2025-01-01", end="2026-06-30")

df = pd.DataFrame({
    "claim_id": range(1, num_records + 1),
    "claim_date": np.random.choice(full_dates, num_records),
    "province": np.random.choice(provinces, num_records),
    "claim_types": np.random.choice(claim_types, num_records),
    "claim_amount": np.random.randint(1000, 50000, num_records),
    "claim_status": np.random.choice(claim_status, num_records)})

df = df.sort_values("claim_date").reset_index(drop=True)

df.head()

,claim_id,claim_date,province,claim_types,claim_amount,claim_status
0,558,2025-01-01,Eastern Cape,Motor Vehicle,44526,Pending
1,734,2025-01-01,Eastern Cape,Motor Vehicle,21810,Approved
2,846,2025-01-01,Western Cape,Business Insurance,49516,Pending
3,475,2025-01-01,Eastern Cape,Home Insurance,21583,Pending
4,153,2025-01-02,Eastern Cape,Motor Vehicle,33793,Pending

df.to_csv("insurance_claims.csv", index=False)

print("Dataset saved successfully")

In [3]:
# View first 5 rows
df.head()

,claim_id,claim_date,province,claim_types,claim_amount,claim_status
0,558,2025-01-01,Eastern Cape,Motor Vehicle,44526,Pending
1,734,2025-01-01,Eastern Cape,Motor Vehicle,21810,Approved
2,846,2025-01-01,Western Cape,Business Insurance,49516,Pending
3,475,2025-01-01,Eastern Cape,Home Insurance,21583,Pending
4,153,2025-01-02,Eastern Cape,Motor Vehicle,33793,Pending

In [4]:
df.info()
df.dtypes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   claim_id      1000 non-null   int64
 1   claim_date    1000 non-null   datetime64[ns]
 2   province      1000 non-null   object
 3   claim_types   1000 non-null   object
 4   claim_amount  1000 non-null   int32
 5   claim_status  1000 non-null   object
dtypes: datetime64[ns](1), int32(1), int64(1), object(3)
memory usage: 43.1+ KB

claim_id                 int64
claim_date      datetime64[ns]
province                object
claim_types             object
claim_amount             int32
claim_status            object
dtype: object

In [5]:
print("=== DATA QUALITY REPORT ===")
print("Rows, Columns:", df.shape)
print("\nMissing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

=== DATA QUALITY REPORT ===
Rows, Columns: (1000, 6)

Missing Values:
claim_id        0
claim_date      0
province        0
claim_types     0
claim_amount    0
claim_status    0
dtype: int64

Duplicate Rows:
0
Number of rows: 1000
Number of columns: 6

In [6]:
print("Minimum claim amount:", df["claim_amount"].min())
print("Maximum claim amount:", df["claim_amount"].max())
print("Average claim amount:", round(df["claim_amount"].mean(),2))
print("Provinces:")
print(df["province"].unique())
print("\nClaim Types:")
print(df["claim_types"].unique())
print("\nClaim Statuses:")
print(df["claim_status"].unique())

invalid_amounts = df[df["claim_amount"] <= 0]
print("Invalid claim amounts:", len(invalid_amounts))

Minimum claim amount: 1082
Maximum claim amount: 49861
Average claim amount: 25598.76
Provinces:
['Eastern Cape' 'Western Cape' 'Northern Cape' 'North West' 'Free State'
 'Limpopo' 'Mpumalanga' 'KwaZulu-Natal' 'Gauteng']

Claim Types:
['Motor Vehicle' 'Business Insurance' 'Home Insurance' 'Life Insurance'
 'Health Insurance']

Claim Statuses:
['Pending' 'Approved' 'Rejected']
Invalid claim amounts: 0

In [7]:
print(df["claim_status"].value_counts())
print(df["province"].value_counts())

claim_status
Rejected    352
Pending     336
Approved    312
Name: count, dtype: int64
province
Free State       130
Western Cape     115
Limpopo          113
North West       112
Eastern Cape     109
KwaZulu-Natal    107
Northern Cape    106
Mpumalanga       104
Gauteng          104
Name: count, dtype: int64

In [8]:
cleaned_df = df.copy()

print("Clean dataset created successfully.")
print("Rows:", cleaned_df.shape[0])
print("Columns:", cleaned_df.shape[1])

Clean dataset created successfully.
Rows: 1000
Columns: 6

In [9]:
cleaned_df.to_csv("insurance_claims_cleaned.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.